export default [
    { label: "Acceso a internet", value: "Acceso a internet", group: "Clasicas" },
    { label: "Protocolos de Bioseguridad", value: "Protocolos de Bioseguridad", group: "Clasicas" },
    { label: "Parqueadero para carros", value: "Parqueadero para carros", group: "Clasicas" },
    { label: "Parqueadero para motocicletas", value: "Parqueadero para motocicletas", group: "Clasicas" },
    { label: "Parqueadero para bicicletas", value: "Parqueadero para bicicletas", group: "Clasicas" },
    { label: "Parqueadero para carros gratis", value: "Parqueadero para carros gratis", group: "Clasicas" },
    { label: "Parqueadero para motocicletas gratis", value: "Parqueadero para motocicletas gratis", group: "Clasicas" },
    { label: "Parqueadero para bicicletas gratis", value: "Parqueadero para bicicletas gratis", group: "Clasicas" },
    { label: "Recepción", value: "Recepción", group: "Clasicas" },
    { label: "Elevador", value: "Elevador", group: "Clasicas" },
    { label: "Buena iluminación", value: "Buena iluminación", group: "Clasicas" },
    { label: "Impresora", value: "Impresora", group: "Tecnología/Conectividad" },
    { label: "Proyector", value: "Proyector", group: "Tecnología/Conectividad" },
    { label: "Televisor", value: "Televisor", group: "Tecnología/Conectividad" },
    { label: "Aire Acondicionado", value: "Aire Acondicionado", group: "Tecnología/Conectividad" },
    { label: "Fotocopiadora", value: "Fotocopiadora", group: "Tecnología/Conectividad" },
    { label: "Escaner", value: "Escaner", group: "Tecnología/Conectividad" },
    { label: "Cargadores", value: "Cargadores", group: "Tecnología/Conectividad" },
    { label: "Bancos de carga", value: "Bancos de carga", group: "Alimentación" },
    { label: "Refrigerador", value: "Refrigerador", group: "Alimentación" },
    { label: "Café Gratis", value: "Café Gratis", group: "Alimentación" },
    { label: "Té Gratis", value: "Té Gratis", group: "Alimentación" },
    { label: "Snacks Gratis", value: "Snacks Gratis", group: "Alimentación" },
    { label: "Venta de Cafe", value: "Venta de Cafe", group: "Alimentación" },
    { label: "Alchol Permitido", value: "Alchol Permitido", group: "Alimentación" },
    { label: "Restaurante", value: "Restaurante", group: "Alimentación" },
    { label: "Bar/Venta de alcohol disponible", value: "Bar/Venta de alcohol disponible", group: "Alimentación" },
    { label: "Cocina", value: "Cocina", group: "Alimentación" },
    { label: "Servicio de cafetería", value: "Servicio de cafetería", group: "Alimentación" },
    { label: "Zona de recreación", value: "Zona de recreación", group: "Diversión/Ocio" },
    { label: "Gimnasio", value: "Gimnasio", group: "Diversión/Ocio" },
    { label: "Espacio de Yoga", value: "Espacio de Yoga", group: "Diversión/Ocio" },
    { label: "Espacio de meditación", value: "Espacio de meditación", group: "Diversión/Ocio" },
    { label: "Zona arcade", value: "Zona arcade", group: "Diversión/Ocio" },
    { label: "Juegos de mesa", value: "Juegos de mesa", group: "Diversión/Ocio" },
    { label: "Libreria", value: "Libreria", group: "Diversión/Ocio" },
    { label: "Masajes", value: "Masajes", group: "Diversión/Ocio" },
    { label: "Lugar para fumar", value: "Lugar para fumar", group: "Diversión/Ocio" },
    { label: "Cabinas telefonicas", value: "Cabinas telefonicas", group: "Zonas" },
    { label: "Espacio para mascotas", value: "Espacio para mascotas", group: "Zonas" },
    { label: "Espacio para maternidad", value: "Espacio para maternidad", group: "Zonas" },
    { label: "Espacios al aire libre", value: "Espacios al aire libre", group: "Zonas" },
    { label: "Sala de estar", value: "Sala de estar", group: "Zonas" },
    { label: "Lugares para dormir", value: "Lugares para dormir", group: "Zonas" },
    { label: "Espacio para llamada", value: "Espacio para llamada", group: "Zonas" },
    { label: "Espacios/Zonas verdes", value: "Espacios/Zonas verdes", group: "Zonas" },
    { label: "Casillero personal", value: "Casillero personal", group: "Zonas" },
    { label: "Terraza", value: "Terraza", group: "Zonas" },
    { label: "Zonas verdes", value: "Zonas verdes", group: "Zonas" },
    { label: "Lugares de AirBnB cercanos", value: "Lugares de AirBnB cercanos", group: "Ubicación" },
    { label: "Estacion de transporte cerca", value: "Estacion de transporte cerca", group: "Ubicación" },
    { label: "Vista al mar", value: "Vista al mar", group: "Ubicación" },
    { label: "Cerca al Centro Comercial", value: "Cerca al Centro Comercial", group: "Ubicación" },
    { label: "Cerca al Aeropuerto", value: "Cerca al Aeropuerto", group: "Ubicación" },
    { label: "Cerca al Centro", value: "Cerca al Centro", group: "Ubicación" },
    { label: "Cerca a zonas verdes", value: "Cerca a zonas verdes", group: "Ubicación" },
    { label: "Cerca a restaurantes", value: "Cerca a restaurantes", group: "Ubicación" },
    { label: "Cerca a estacion de policias", value: "Cerca a estacion de policias", group: "Ubicación" },
    { label: "Servicio de limpieza", value: "Servicio de limpieza", group: "Servicios" },
    { label: "Primeros Auxilios", value: "Primeros Auxilios", group: "Servicios" },
    { label: "Servicio de correo", value: "Servicio de correo", group: "Servicios" },
    { label: "Tablero acrilico con marcadores", value: "Tablero acrilico con marcadores", group: "Servicios" },
    { label: "Tablero de notas/noticias", value: "Tablero de notas/noticias", group: "Servicios" },
    { label: "Servicio 24 horas", value: "Servicio 24 horas", group: "Servicios" },
    { label: "Sillas tipo Puff", value: "Sillas tipo Puff", group: "Servicios" },
    { label: "Sillas ergonómicas", value: "Sillas ergonómicas", group: "Servicios" },
    { label: "Servicio días festivos", value: "Servicio días festivos", group: "Servicios" },
    { label: "Servicio todos los días", value: "Servicio todos los días", group: "Servicios" },
    { label: "Permite Mascotas", value: "Permite Mascotas", group: "Servicios" },
    { label: "Seguridad Privada", value: "Seguridad Privada", group: "Servicios" },
    { label: "Duchas", value: "Duchas", group: "Servicios" }
]